### ISSUE TITLE
MathML in Chromium Roadmap

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#19]
These are high-level technical outcomes. Further details may be provided in the sections below.

* [x] Rendering of mathematical formulas in display and inline mode.
* [x] Right-to-left rendering of formulas. #41
* [x] Experiment vertical layout of formulas. #41
* [x] Rendering of text using OpenType fonts, including non-latin characters (e.g. Arabic or Asian), math variants (math italic, double struck, fraktur...), math operators (e.g. largeop or stretchy).
* [x] Built-in dictionary for operator properties as well as the corresponding user-specified attributes.
* [x] Spacing using operator-based rules or user-specified elements.
* [x] Layout of fractions, roots, underscripts, overscripts, postscripts and prescripts using OpenType parameters and automatic script level.
* [x] Basic HTML-like implementation of tables.
* [x] Special markup for annotations (e.g. LaTeX) and errors (e.g. from LaTeX
      converters) or styling (including foreground/background colors and text size).
* [x] Compatibility with HTML5 (CSS styling, embedding in HTML pages or SVG
images, dynamic modification via DOM and JavaScript) #36 #28 #42 

This was the initial MathML implementation roadmap from https://mathml.igalia.com/project/#roadmap:

### 1) Basic Setup

We will create basic classes for the following MathML elements as well as simple layout using LayoutNG. Right-to-left and vertical layout should be taken into account from the beginning.

* [x] Simple grouping `<math>` (with its `display` attribute), `<mrow>`, `<mstyle>`, `<merror>` (with special CSS style), `<mpadded>`, `<mphantom>` (with `visibility: hidden`), `<menclose>`.  #3 
* [x] Simple text container: `<mi>`, `<mn>`, `<mo>`, `<mtext>` and `<ms>`. #4 
* [x] Simple spacing: `<mspace>` element with `width`, `depth`, `height` attributes. #5 
* [x] `dir`, `mathcolor`, `mathbackground` and `mathsize` attributes #6 
* [x] Simplified `semantics`: just display the first child and hide annotations. #7 

### 2) Basic Layout

We will create partial implementation of some layout elements. Some, but not all OpenType MATH constants will be used. During this step, `displaystyle` is assumed to be true while `scriptlevel` is not incremented.

* [x] Fraction (`<mfrac>`), with its `linethickness` attribute. #8 
* [x] Postscripts: `<msub>`, `<msup>`, `<msubsup>` #9 
* [x] Under and over scripts: `<munder>`, `<mover>`, `<munderover>` #10 
* [x] Multiple pre and post scripts: `<mmultiscripts>` #11 
* [x] Basic HTML-like implementation of `mtable`. #12 
* [x] Advanced Spacing: `mpadded` with simplified interpretation of `width`, `depth`, `height`, `lspace` and `voffset`. #13 

### 3) Operator Dictionary

We will import the operator dictionary from WebKit and implement the following `<mo>` attributes:

* [x] `form` (for selecting an entry in the dictionary) #16 
* [x] `accent`, `largeop` and `movablelimits` (to perform spacing in under and over scripts) #17 
* [x] `lspace` and `rspace` (to perform spacing in `<mrow>`-like elements). #18 

### 4) Stretchy operators

This is an important step during which the following tasks will be performed:

* [x] Shaping large and stretchy operators using the `MathVariants` table. See [this blog post](http://frederic-wang.fr/opentype-math-in-harfbuzz.html) for a shaping algorithm. #20 
* [x] Drawing of `largeop` operators in under and over scripts (again, we assume `displaystyle` to be true for now). #21 
* [x] Stretch logic in `<mrow>`-like elements and under and over scripts. #22 
* [x] Using `stretchy` and `symmetric` attributes. #23 
* [x] Simple embellished operators #24 
* [x] Roots (`msqrt`, `mroot`): Some, but not all OpenType MATH constants will be used. During this step, `displaystyle` is assumed to be true while `scriptlevel` is not incremented. #25 

### 5) Advanced Style

The following attributes will be considered:

* [x] `mathvariant` #1 
* [x] `displaystyle` #14 
* [x] `scriptlevel` #15

**Comment by fred-wang** [comment]
Closing since things are essentially done.
